###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:
    memcached:
        image: 'memcached:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        env_file:
            # https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information
            - path: .env
              required: true # default
            - path: .env.local
              required: false
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build:
            context: .
            dockerfile: ./phpdocker/php-fpm/Dockerfile
        working_dir: /application
        volumes:
            - /application/vendor
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
